#!/bin/sh

# Package
PACKAGE="RoonServer"
# Others
SSS="/var/packages/${PACKAGE}/scripts/start-stop-status"
ROON_PKG_URL="http://download.roonlabs.com/builds/RoonServer_linuxx64.tar.bz2"
INOTIFY_DIR="/usr/local/inotify-tools"
PATH="${INOTIFY_DIR}/bin:${PATH}"

preinst ()
{
  	ROON_DATA_DIR=`${SYNOPKG_PKGINST_TEMP_DIR}/helper-scripts/getsharelocation RoonServer`

    if [[ -f ${ROON_DATA_DIR}/ROON_DEBUG_INSTALL_URL.txt ]]; then
        ALPHA=$(<${ROON_DATA_DIR}/ROON_DEBUG_INSTALL_URL.txt)
        
        if [[ ${ALPHA:0:4} == "http" ]]  && [[ $(basename ${ALPHA}) == $(basename ${ROON_PKG_URL}) ]]; then
            ROON_PKG_URL="${ALPHA}"
        fi
    fi

    if [ "${SYNOPKG_PKG_STATUS}" != "UPGRADE" ]; then 
    	pushd /tmp
		rm -f RoonServer_linuxx64.tar.bz2
		curl -s -O "${ROON_PKG_URL}"
		R=$?
		if [ $R -eq 0 ]; then
			tar xjf RoonServer_linuxx64.tar.bz2 -C "${SYNOPKG_PKGINST_TEMP_DIR}"
			R=$?
		fi
		rm -f RoonServer_linuxx64.tar.bz2
		popd
		if [ $R -ne 0 ]; then
			echo "Could not download installation archive from Roon Labs website. Please check your internet connection."
		fi
		return $R
    fi
}

postinst ()
{
	ln -s ${SYNOPKG_PKGDEST}/roon-inotify-tools ${INOTIFY_DIR}
	
	ln -s ${INOTIFY_DIR}/lib/libinotifytools.so.0.4.1 ${INOTIFY_DIR}/lib/libinotifytools.so
	ln -s ${INOTIFY_DIR}/lib/libinotifytools.so.0.4.1 ${INOTIFY_DIR}/lib/libinotifytools.so.0

	
	mkdir -p /usr/local/bin
	ln -s ${INOTIFY_DIR}/bin/inotifywait /usr/local/bin/inotifywait
	ln -s ${INOTIFY_DIR}/bin/inotifywatch /usr/local/bin/inotifywatch
	exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null
    
}

postuninst ()
{
    # Delete Package directory if it contains nothing.
    if [ ! -d "$(ls -A /usr/syno/etc/packages/${PACKAGE})" ]; then
        rm -Rf /usr/syno/etc/packages/${PACKAGE}
    fi
    
    rm -f ${INOTIFY_DIR}
	rm -f /usr/local/bin/inotifywait
	rm -f /usr/local/bin/inotifywatch
    exit 0
}

preupgrade ()
{
    mv ${SYNOPKG_PKGDEST}/RoonServer ${SYNOPKG_PKGINST_TEMP_DIR}/RoonServer
    exit 0
}

postupgrade ()
{
    exit 0
}
