#!/bin/sh

# Package
PACKAGE="RoonServer"
DNAME="RoonServer"
# Others
SSS="/var/packages/${PACKAGE}/scripts/start-stop-status"
ROON_PKG_URL="http://download.roonlabs.com/builds/RoonServer_linuxx64.tar.bz2"

preinst ()
{

    if [ "${SYNOPKG_PKG_STATUS}" != "UPGRADE" ]; then 
	    curl "${ROON_PKG_URL}" | tar xvj -C ${SYNOPKG_PKGINST_TEMP_DIR} > /dev/null 2>&1
    fi
}

postinst ()
{
	exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null
    
}

postuninst ()
{
    ## Add an option to export logfiles (like library export)!

    # Delete Package directory if it contains nothing.
    if [ ! -d "$(ls -A /usr/syno/etc/packages/${PACKAGE})" ]; then
        rm -Rf /usr/syno/etc/packages/${PACKAGE}
    fi

    exit 0
}

preupgrade ()
{
    mv ${SYNOPKG_PKGDEST}/RoonServer ${SYNOPKG_PKGINST_TEMP_DIR}/RoonServer
    exit 0
}

postupgrade ()
{
    exit 0
}
