#!/bin/sh
PACKAGE="RoonServer"
ROON_MNT_DIR="/var/packages/${PACKAGE}/target/mnt"
SHARE_CONF_LOC="/usr/syno/etc/share_right.map"
CMD_INOTIFYWAIT="/var/packages/${PACKAGE}/target/inotify-tools/bin/inotifywait"

rebuild_symlinks() {
SHARE_CONF=`cat "${SHARE_CONF_LOC}" | awk -F ' *= *' '{ if ($1 ~ /^\[/) section=$1; else if ($1 !~ /^$/) print $1 section "=" $2 }'`

## Remove old SymLinks
rm "$ROON_MNT_DIR"/*
ls "$ROON_MNT_DIR"

### CHECKING THE SHARE CONFIG FILE FOR ROONSERVER SHARES AND GET THEIR GUID
SHARE_ID=($(echo "${SHARE_CONF}" | egrep 'display[[:space:]]name.*$' | cut -d "[" -f2 | cut -d "]" -f1))
SHARE_PATH=($(echo "${SHARE_CONF}" | egrep 'path=.*$' | cut -d "[" -f2 | cut -d "]" -f1))

### Check if Section contains a path
if [[ ${#SHARE_ID[@]} -ne 0  ]]; then
   for i in ${SHARE_ID[@]} 
   do
      currentObject=$i
      GUID=`echo "${SHARE_CONF}" | grep "path\[$currentObject\]" | cut -d "=" -f 2`
      if [[ $i != *"|"* ]]
	  	then
	  	echo "$i: "$GUID;
		ln -s "$GUID" "$ROON_MNT_DIR"
	  fi
   done
fi

### esata shares
ACTIVE_SATASHARE=($(df | grep "/volumeSATA[0-9]/satashare" | awk '{print $6}'))
for i in ${ACTIVE_SATASHARE[@]}
   do
   ln -s "$i" "$ROON_MNT_DIR"
   echo "$(basename $i): $i"
#   STORAGE_SERIAL=`hdparm -I $i | grep "Serial Number" | awk '{print $3}'`
#   GUID=`echo "${SHARE_CONF}" | grep "path\[$STORAGE_SERIAL" | cut -d "=" -f 2`
#   echo "GUID=$GUID"
#   if [[ $i != *"|"* ]];  then
#      echo "$i: "$GUID;
#      ln -s "$GUID" "$ROON_MNT_DIR"
#   fi
done
#echo ${ACTIVE_SATASHARE[@]}
#STORAGE_SERIAL=`hdparm -I ${ACTIVE_SATASHARE[0]} | grep "Serial Number" | awk '{print $3}'`
#echo $STORAGE_SERIAL
}
rebuild_symlinks

while true; do
	$CMD_INOTIFYWAIT -e modify,delete_self "$SHARE_CONF_LOC" | while read xx; do
		echo "Modification detected!"
		sleep 1 
		rebuild_symlinks
	done
done

